version: '3.3'
services:
  jira:
    image: tomaszbar/jira-installer
    ports: 
      - '8080:8080'
    expose: 
      - '8080'
  db:
    image: tomaszbar/jira-mssql-empty-db
    ports: 
      - '1433:1433'
    expose:
      - '1433' 