version: '3.3'
services:
  db:
    image: tomaszbar/jira-postgres-empty-db
    restart: always
    expose: 
      - '5432'
  jira:
    depends_on:
     - db
    image: tomaszbar/jira-installer
    restart: always
    ports: 
      - '8080:8080'
    expose: 
      - '8080'
