version: '3.3'
services:
  jira:
    depends_on:
     - db
    build:
      context: ../jira-autorun
      args: 
        JIRA_NAME: "atlassian-jira-software-8.0.0-x64.bin"
    ports: 
      - '8080:8080'
      - '5006:5006'
    expose: 
      - '8080'