version: '3.3'
services:
  jira:
    image: tomaszbar/jira-installer
    ports: 
      - '8080:8080'
    expose: 
      - '8080'
  db:
    image: tomaszbar/jira-oracle-empty-db
    ports: 
      - '1521:1521'
    expose:
      - '1521' 