version: '3.3'
services:
  jira:
    depends_on:
     - db
    build:
      context: ../jira-autorun
      args: 
        JIRA_NAME: "atlassian-jira-software-7.9.0-x64.bin"
    ports: 
      - '8080:8080'
    expose: 
      - '8080'
    volumes:
      - /tmp/jira:/var/atlassian/application-data/Jira
  db:
    image: tomaszbar/jira-mysql-empty-db
    ports:
      - '3306:3306'
    expose: 
      - '3306'
