version: '3.3'
services:
  jira:
    depends_on:
     - db
    build:
      context: ../jira-autorun
      args: 
        JIRA_NAME: "atlassian-jira-software-8.3.0-x64.bin"
    ports: 
      - '8080:8080'
      - '5005:5005'
    expose: 
      - '8080'
  db:
    image: tomaszbar/jira-postgres-empty-db
    restart: always
    expose: 
      - '5432'
